version: '2'
services:
  web:
    restart: always
    image: mangar/jekyll:1.1
    volumes:
      - .:/app
    ports:
      - 4000:4000
    command: bash -c "bundle install; bundle exec jekyll serve"
